FROM python:3.11

WORKDIR /app

COPY src/common src/common
COPY src/runner src/runner
COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app/src
ENV KAFKA_BOOTSTRAP_SERVERS=kafka:9092
ENV POSTGRES_SCENARIOS_HOST=scenarios-db
ENV POSTGRES_PREDICTIONS_HOST=predictions-db
ENV POSTGRES_SCENARIOS_PORT=5432
ENV POSTGRES_PREDICTIONS_PORT=5432

CMD bash -c "echo '[Runner] Waiting 30 seconds for Kafka...'; sleep 30; python src/runner/main.py"
