FROM python:3.11

WORKDIR /app

COPY src/common src/common
COPY src/inference src/inference
COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app/src
ENV PYTHONUNBUFFERED=1
ENV KAFKA_BOOTSTRAP_SERVERS=kafka:9092

CMD bash -c "echo '[Inference] Waiting 30 seconds for Kafka...'; sleep 30; python src/inference/main.py"